
FROM debian:bookworm

RUN apt-get update && apt-get upgrade && apt install -y mariadb-server

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

EXPOSE ${MYSQL_PORT}

ENTRYPOINT ["/entrypoint.sh"]

CMD ["sh", "-c", "mysqld --user=mysql --bind-address=0.0.0.0 --port=${MYSQL_PORT}"]
