FROM debian:bookworm

RUN apt-get update && apt-get upgrade && su root

RUN apt install nginx -y && apt install systemctl -y

#COPY . .

COPY nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /etc/nginx/certs && \
	openssl req -x509 -nodes -days 365 \
	-newkey rsa:2048 \
	-keyout /etc/nginx/certs/server.key \
	-out /etc/nginx/certs/server.crt \
	-subj "/CN=localhost"

EXPOSE 443

#CMD ["yes"]

CMD ["nginx", "-g", "daemon off;"]
