events {}

http {
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

	root /var/www/html;

	index index.php index.html;


        location / {
		      # 1. try the exact file requested ($uri)
            # 2. try it as a directory ($uri/)
            # 3. fall back to WordPress router (index.php)
            #    $args passes the query string along (?page_id=2 etc)
            try_files $uri $uri/ /index.php?$args;
        }

	location ~ \.php$ {
	    # Forward to PHP-FPM in the wordpress container
            # "wordpress" is resolved by Docker DNS to that container's IP
            fastcgi_pass wordpress:9000;

            # If URL is a directory, try index.php inside it
            fastcgi_index index.php;

            # Load standard FastCGI parameters (REQUEST_METHOD, etc.)
            include fastcgi_params;

            # Tell PHP-FPM the full path of the file to execute
            # $document_root = the root directive above (/var/www/html)
            # $fastcgi_script_name = the .php file being requested
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
